project:
  type: website
  output-dir: docs

website:
  favicon: images/logo.gif
  navbar:
    background: primary
    title: false
    left:
      - text: "Home"
        file: index.qmd
      - text: "Training"
        file: training/training.qmd
      - sidebar:software
      - sidebar:resources
      - sidebar:about
      - text: "News"
        file: posts.qmd

    right: 
      - icon: twitter-x
        href: https://twitter.com/distancesamp
      - icon: github
        menu:
          - text: Repositories
            url: https://github.com/distancedevelopment
          - text: Report a bug (Distwin)
            url: https://github.com/DistanceDevelopment/distance-bugs/issues
          - text: Report a bug (R package)
            url: https://github.com/DistanceDevelopment/Distance/issues
      - icon: envelope
        href: mailto:distance@st-andrews.ac.uk
        
  sidebar: 
    - id: software
      title: "Software"
      contents: 
        - software/downloaddistwin.qmd
        - software/Rpackages.qmd
        - software/activity.qmd

    - id: resources
      title: "Resources"
      contents: 
        - resources/citations.qmd
        - resources/whatisds.qmd
        - resources/books_and_papers.qmd
        - resources/distancelist.qmd
        - resources/bibliography/dbib.qmd
        - resources/vignettes.qmd
      
    - id: about
      title: "About"    
      contents: 
        - about/authors.qmd
        - about/distancesponsors.qmd
        - about/distancehistory.qmd


  page-footer:
    background: light
    left: |
      **Distance for Windows citation:** <br>
      Thomas, L., S.T. Buckland, E.A. Rexstad, J.L. Laake, <br>
      S. Strindberg,S.L. Hedley, J.R.B. Bishop, T.A. Marques, <br>
      and K.P. Burnham. 2010. Distance software: design and <br>
      analysis of distance sampling surveys for estimating <br>
      population size. Journal of Applied Ecology 47: 5-14. <br>
      DOI: [10.1111/j.1365-2664.2009.01737.x](https://besjournals.onlinelibrary.wiley.com/doi/full/10.1111/j.1365-2664.2009.01737.x)
    center: |
      **Contact us via email** <br>[distance@st-andrews.ac.uk](mailto:distance@st-andrews.ac.uk) <br>
      We improve our site and software support by using <br>
      Microsoft Clarity to see how you use our website. <br>
      By using our site, you agree that we and Microsoft <br>
      can collect and use this data. Clarity is GDPR compliant.
    right: |
      **Distance R package citation:** <br>
      Miller, D.L., Rexstad, E., Thomas, L., Marshall, L., <br>
      and Laake, J.L. (2019). Distance Sampling in R. <br>
      Journal of Statistical Software, 89(1), 1–28. <br>
      DOI: [10.18637/jss.v089.i01](https://doi.org/10.18637/jss.v089.i01) <br>
    

format:
  html:
    theme: 
      - cosmo
      - eric_theme.scss
    css: styles.css
    mainfont: sans-serif
    toc: true
    include-in-header: 
      - file: clarity.text



