---
title: Training in distance sampling methods
---

Our training in design and analysis of distance sampling surveys take two forms: 

### Guided training workshops
- offered online via Microsoft Teams or Zoom

:::{.callout-important collapse=false appearance='default' icon=true}
## Current offerings
- [Camera trap distance sampling](https://workshops.distancesampling.org/ctds-may-2024) 27-31 May 2024
  - Registration is now open; follow [this link to register](https://onlineshop.st-andrews.ac.uk/conferences-and-events/events/mathematics-statistics/online-workshop-analysis-of-camera-trap-data-with-distance-sampling-27th31st-may-2024). Registration closes on 15th May or when the workshop is full, whichever occurs first
- Introductory distance sampling
  - Likely offered in October 2024 (registration opening in August)
:::

[Email us](mailto:distance@st-andrews.ac.uk) if you are interested in workshops on  introduction to distance sampling or practical design and simulation.


### Asynchronous introductory workshops
- lectures and practical exercise are available online to investigate and review at your own pace.
- [materials](https://workshops.distancesampling.org/async2024-2/) were completely revised in 2024 and cover the following
  - line and point transects
  - assessing and improving precision of abundance estimates
  - introductory survey design
  - stratification and use of covariates in detection function models
  - indirect surveys and multipliers
  - animals that occur in groups
  - double observer methods (for estimating detection probability on the line ($\widehat{g(0)}$))
  - applying appropriate field methods
