---
title: Distance 8.0 download
---

# Download Distance 8.0

[Screenshots of Distance can be found here.](DistWin_images.qmd)

Distance 8.0 is now released as the latest version in the Distance for Windows release cycle. This version of Distance uses an updated msi insaller. It continues to run the 64 bit R allowing users to use R versions 4.2 and up (previous versions of Distance only ran 32 bit R). 
 
Projects will now open in Distance 8.0 by default and you will be asked to "upgrade" your project when opened in Distance 8.0. See the release notes below for more information.

## Download instructions

Please read the "Use Agreement" below before downloading.

**Before installing Distance 8.0, we recommend you read the [latest release notes](relnote.qmd).**

After installing Distance 8.0 you should check the "Additional information" section, below, for any patches that fix last-minute problems.

If you want to make use of the density surface modelling (DSM), mark-recapture distance sampling (MRDS) or multi-analysis (MA) analysis engines or the simulation engine, you need to have the free statistics software R installed on your computer. Note also that only specific versions are supported: for the versions currently supported by Distance, see below.

## Use Agreement

As a user of this software, you are entitled to copy the program and its associated components for your own or your local institutions use (e.g., university, laboratory, department, research center). You are not allowed to distribute this software under the name Distance or any other name, singly or as part of a package, from which you derive any reimbursement.

> Distance contains components and uses technology from many sources: Compaq Computer Corp., ComponentOne Inc., Data Dynamics Inc., Desaware Inc., ESRI, Farpoint Software Inc., IMSL Inc., Microsoft Corp., Polar Software, Sheriden Software Inc. The authors of these components retain copyright over them; however they should not be held responsible for the contents or use of this program, nor should they be contacted with regards to any problems with its use.

We, and our respective agencies, make no warranties, expressed or implied, with respect to this software and its fitness for any particular purpose. In no event will we be liable for indirect or consequential damages, including, without limitation, loss of income or use of information.

Bugs or suggested enhancements should be reported at the [Distance issue tracker](https://github.com/distancedevelopment/distance-bugs). We are keen to hear from you directly regarding any installation issues, please E-mail us at [distance@st-andrews.ac.uk](mailto:distance@st-andrews.ac.uk). This E-mail address can also be used to contact us regarding other feedback.

## Download

<!--
Download Distance 8.0 Release 1 <a href="https://app.onlinesurveys.jisc.ac.uk/s/standrews/distance-8-0-release-1-download" target="_blank">here</a>
-->

[Download Distance 8.0 Release 1](https://app.onlinesurveys.jisc.ac.uk/s/standrews/distance-8-0-release-1-download){.btn .btn-primary .btn role="button" data-toggle="tooltip" title="Standalone Windows software"}
 
Once you have downloaded the file, simply run it to launch the setup program, and then follow the instructions displayed on your screen.  A reboot may be required, in which case you may need to restart the setup program again. 

### Additional information

* The R libraries supplied with Distance 8.0 release 1 were compiled and tested under R version 4.4.1. We recommend you install this version of R, running Distance with older versions of R will lead to warning messages. Newer versions of R may work, but there is no guarantee of this.
* If you're having problems with using the MRDS, DSM and MA analysis engines or the simulation engine (errors regarding check that R is installed correctly or the library directory is not writable) then check [details of R installation for Distance 8.0 Release 1](distwin_installdetails.qmd).


