---
title: Training in distance sampling methods
---

Our training in design and analysis of distance sampling surveys take two forms:

### Guided training workshops

- Offered periodically online via Microsoft Teams or Zoom. These workshops feature live online interactive lectures and Question and Answer sessions with self-paced computer practicals.

:::{.callout-tip collapse=false appearance='default' icon=true}
## Current offerings

- Introductory distance sampling
  - [17-28 February 2025](announcements/intro-feb-2025.md) (registration opening in November 2024)
:::

We offer widening participation scholarships for our guided training workshops. See details and application procedures [at this link](scholarships.qmd).

[Email us](mailto:distance@st-andrews.ac.uk) if you are interested in workshops on introduction to distance sampling, camera trap distance sampling or practical design and simulation.

### Free online course
- lectures and practical exercise are available online to investigate and review at your own pace.
- materials were completely revised in 2024 and cover:
  - line and point transects
  - assessing and improving precision of abundance estimates
  - introductory survey design
  - stratification and use of covariates in detection function models
  - indirect surveys and multipliers
  - animals that occur in groups
  - double observer methods (for estimating detection probability on the line or point, g(0))
  - applying appropriate field methods
  
[Visit online course](https://distancesampling.org/online-course){.btn .btn-primary .btn-lg role="button" data-toggle="tooltip" title="free online course"}